# Generated by Django 5.2.5 on 2025-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
