version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   - DEBUG=1
    #   - DB_NAME=deliverydb
    #   - DB_USER=myuser
    #   - DB_PASSWORD=mypassword
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - SECRET_KEY=your_secret_key_here

volumes:
  postgres_data:
